### ISSUE TITLE
Arguments on is_helper_function

### ISSUE THREAD

**Issue by fernando-alves** [mavcunha/devcli#6]
Hi

devcli command was silently failing when I tried to create a new cli:

```
➜ fjunior:devcli[master]$ ./devcli create -n foo -d /tmp/foo
➜ fjunior:devcli[master]$
```

After some debugging I found out that the script returned after `is_helper_function` execution:

```
➜ fjunior:devcli[master]$ bash -x ./devcli create -n foo -d /tmp/foo
(...)
++ is_help_mode
++ [[ -z '' ]]
++ return
+ [[ -n foo -d /tmp/foo == \h\e\l\p ]]
+ [[ -z -n foo -d /tmp/foo ]]
```
As far as I understood the function expands the arguments and check if there are empty:
```
function is_help_mode() {
  [[ -z "${@}" || "${1}" == 'help' ]]
}
```
That works fine when you use it within the main command, `devcli`. But as `create` is invoked that reference does not work and the argument list is always empty:
```
➜ fjunior:devcli[master]$ ./devcli create -n foo -d /tmp/foo
On create script -n foo -d /tmp/foo
On is help
```
I've fixed it by explicitly passing the arguments to the function:
```
# skip if no argument was given or help needed.
is_help_mode "${@}" && return
```
I'm not sure if that's how it was meant to be used, specially after reading the previous discussion [on this pull request](https://github.com/mavcunha/devcli/pull/4).

Happy to help and/or open a PR with the fix, but I wanted to check with there was a better way to solve it first.

**Comment by fernando-alves** [comment]
Hi

devcli command was silently failing when I tried to create a new cli:

```
➜ fjunior:devcli[master]$ ./devcli create -n foo -d /tmp/foo
➜ fjunior:devcli[master]$
```

After some debugging I found out that the script returned after `is_helper_function` execution:

```
➜ fjunior:devcli[master]$ bash -x ./devcli create -n foo -d /tmp/foo
(...)
++ is_help_mode
++ [[ -z '' ]]
++ return
+ [[ -n foo -d /tmp/foo == \h\e\l\p ]]
+ [[ -z -n foo -d /tmp/foo ]]
```
As far as I understood the function expands the arguments and check if there are empty:
```
function is_help_mode() {
  [[ -z "${@}" || "${1}" == 'help' ]]
}
```
That works fine when you use it within the main command, `devcli`. But as `create` is invoked that reference does not work and the argument list is always empty:
```
➜ fjunior:devcli[master]$ ./devcli create -n foo -d /tmp/foo
On create script -n foo -d /tmp/foo
On is help
```
I've fixed it by explicitly passing the arguments to the function:
```
# skip if no argument was given or help needed.
is_help_mode "${@}" && return
```
I'm not sure if that's how it was meant to be used, specially after reading the previous discussion [on this pull request](https://github.com/mavcunha/devcli/pull/4).

Happy to help and/or open a PR with the fix, but I wanted to check with there was a better way to solve it first.

**Comment by mavcunha** [comment]
PR #7 fixes this issue.
