### ISSUE TITLE
Create command is not present anymore

### ISSUE THREAD

**Issue by rafalima** [mavcunha/devcli#9]
I'm trying to create a new cli, but the create command as described in the README is not working anymore

Steps
* execute `./devcli create -n mytool -d ~/Projects/myproject`

**Actual result**: "'create' not found"

Extra information: 
* Looking at the code, I found a `twin create` command, however, this command creates a symbolic link to the original devli executable.
* This does not block me from using the CLI as I can copy it myself and delete the code I don't need, however, I will be using this devcli for a video tutorial that I'm doing and it would be great to have the create functionality back, because it will be much easier for people to use it.

**Comment by rafalima** [comment]
I created a PR for this https://github.com/mavcunha/devcli/pull/11

**Comment by mavcunha** [comment]
After two years, I'm back on giving some attention to this project. The new version won't need to create new tools but will work by extension.
